# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
       
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test_pkgr:
    runs-on: ubuntu-latest
    steps:
      - name: Testing the pkgr
        run: |
          sudo wget https://github.com/metrumresearchgroup/pkgr/releases/download/v3.1.0/pkgr_3.1.0_linux_amd64.tar.gz -O /tmp/pkgr.tar.gz
          sudo tar xzf /tmp/pkgr.tar.gz pkgr
          sudo mv pkgr /usr/local/bin/pkgr
          sudo chmod +x /usr/local/bin/pkgr
          pkgr
  call-workflow:
    uses: ./.github/workflows/sample_pkgr.yml
    secrets: inherit
    with:
      release_tag: 2022q26
      baseos_tag: 8
  call-workflow1:
    needs: call-workflow
    uses: ./.github/workflows/sample2.yml
    with:
      release_tag: ${{ needs.call-workflow.outputs.output1 }}
    secrets: inherit
