
# This is a basic workflow to help you get started with Actions

name: sample

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      release_tag:
        description: "Defines the release tag for each layers"
        required: true
        type: string
      baseos_tag:
        description: "Defines the initial base os tag"
        required: true
        type: string
    outputs:
      output1:
        description: "Passing the release tag for this layer"
        value: ${{ jobs.build-and-push.outputs.tag }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    startup:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      defaults:
        run:
          shell: bash
    steps:
      # Set up AWS Credentials so you can have permission to call lambda
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::794795657660:role/CUSPFE-RSTUDIO-GBL-GITHUB-ACTIONS-RUNNER-ROLE
          aws-region: us-east-1
      # Trigger self-hosted runner by calling lambda to build container
      - name: Trigger Self Hosted Runner
        uses: pfizer-analytics/rstudio-github-actions-tools/actions/create-runner@v1
        with:
          repository: ${{ github.repository }}
          gh_pat: ${{ secrets.GH_PAT }}
          labels: rstudio-docker-demo
  build-and-push:
     runs-on: ubuntu-latest
     outputs:
      tag: ${{ steps.release_tag.outputs.tag }}
     steps:      
      - name: Checkout 
        uses: actions/Checkout@v3
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}

      - name: Setting up date environment variable
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - name: Setting up release tag for this layer
        id: release_tag
        run: |
          echo "tag=${{ inputs.release_tag }}-${{ env.date }}" >> $GITHUB_ENV
          echo "tag=${{ inputs.release_tag }}-${{ env.date }}" >> $GITHUB_OUTPUT
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./baseos/
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}
          tags: bala001/centos:${{ env.tag }}
          build-args: |
            RELEASE_TAG=${{ inputs.baseos_tag }}
