# This is a basic workflow to help you get started with Actions

name: OS_Utilities

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/Checkout@v3
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}

      - name: Test with environment variables
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./OS_Utilities/
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}
          tags: bala001/cp-os-utilities:2022q26-${{ env.date }}
