
# This is a basic workflow to help you get started with Actions

name: sample

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      release_tag:
        description: "Defines the release tag for each layers"
        required: true
        type: string
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
     runs-on: ubuntu-latest
     steps:      
      - name: Checkout 
        uses: actions/Checkout@v3
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}

      - name: Setting up date environment variable
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-contexts: tag=8
          push: true
          context: ./baseos/
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}
          tags: bala001/centos:2022q26-${{ env.date }}
