# This is a basic workflow to help you get started with Actions

name: self-host-runner-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/Checkout@v3
    
    - name: uploading the file to release page
      run: |
        gh release create R-4.1.3_ImproveR ./cp-pkpd-2023q21.exe --notes "Automation build image sample"
        
       
      # Set up AWS Credentials so you can have permission to call lambda
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: arn:aws:iam::794795657660:role/CUSPFE-RSTUDIO-GBL-GITHUB-ACTIONS-RUNNER-ROLE
#           aws-region: us-east-1
#       - name: Testing github repo
#         run: echo ${{ github.repository }}
# #       Trigger self-hosted runner by calling lambda to build container
#       - name: Trigger Self Hosted Runner
#         uses: pfizer-analytics/rstudio-github-actions-tools/actions/create-runner@v1
#         with:
#           repository: ${{ github.repository }}
#           gh_pat: ${{ secrets.GH_PAT }}
#           labels: self-hosted-runner
